# -*- coding: utf-8 -*-
"""
CFA Prep CLI - IPS builder module
Author: CodeBuddy AI Assistant
Purpose: Generate CFA L3 personal and institutional Investment Policy Statement (IPS) templates,
         outputting Markdown to the data/templates/ directory.
"""

from pathlib import Path
from typing import Optional

from .utils import (
    get_data_dir,
    write_file_text,
    read_file_text,
    today_iso,
)


# Personal IPS template content
IPS_PERSONAL_TEMPLATE = """# Individual Investment Policy Statement (Individual IPS)

> Generated: {date}
> CFA Level III Study Tool

---

## 1. Client Profile

- **Name**: (fill in)
- **Age**: (fill in)
- **Occupation**: (fill in)
- **Family status**: (fill in)
- **Investment experience**: (fill in)

---

## 2. Return Requirement

| Category | Description |
|------|------|
| **Target return** | (fill in a specific value or range) |
| **Return source** | Capital appreciation / Current income / Total return |
| **Constraints** | Inflation adjustment / After-tax return requirement |

**Analysis**: (fill in detailed analysis)

---

## 3. Risk Tolerance

| Factor | Assessment |
|------|------|
| **Objective capacity** | High / Medium / Low (based on asset size, income stability, etc.) |
| **Subjective willingness** | High / Medium / Low (based on client interviews and questionnaires) |
| **Overall conclusion** | Above average / Average / Below average |

**Key considerations**:
- (list the key factors affecting risk tolerance)
- (e.g., investment horizon, liquidity needs, etc.)

---

## 4. Time Horizon

| Stage | Period | Characteristics |
|------|--------|------|
| **Stage 1** | (e.g., 15 years before retirement) | Accumulation phase |
| **Stage 2** | (e.g., 20 years after retirement) | Distribution phase |

**Multi-stage analysis**: (fill in)

---

## 5. Liquidity Requirements

| Requirement type | Amount/ratio | Time |
|----------|-----------|------|
| **Emergency reserve** | | |
| **Large expenditures** | | |
| **Ongoing cash flow needs** | | |

**Analysis**: (fill in)

---

## 6. Legal & Regulatory

| Item | Description |
|------|------|
| **Tax considerations** | Income tax / Capital gains tax / Estate tax |
| **Legal restrictions** | (e.g., trust terms, legal entity restrictions) |
| **Regulatory requirements** | (e.g., SEC registration requirements) |

---

## 7. Unique Circumstances

- (e.g., ESG/socially responsible investing preferences)
- (e.g., restrictions on specific industry stocks)
- (e.g., handling of family business shares)
- (other personalized needs)

---

## 8. Asset Allocation

| Asset class | Target weight | Range |
|----------|----------|------|
| Equity | | |
| Fixed income | | |
| Alternative investments | | |
| Cash | | |

**Rebalancing strategy**: (fill in)

---

## 9. Benchmark

- **Composite benchmark**: (e.g., 60% S&P 500 + 40% Bloomberg Agg)
- **Per-asset-class benchmarks**: (list)

---

## 10. Monitoring & Review

- **Review frequency**: Quarterly / Semi-annually / Annually
- **Trigger conditions**: (deviation from target weight > X% / significant change in client circumstances)
- **Report content**: (fill in)

---

*This template was auto-generated by CFA Prep CLI*
"""

# Institutional IPS template content
IPS_INSTITUTIONAL_TEMPLATE = """# Institutional Investment Policy Statement (Institutional IPS)

> Generated: {date}
> CFA Level III Study Tool

---

## 1. Institution Profile

- **Institution type**: Pension fund / Foundation / Endowment / Insurance company / Bank / Other
- **Institution name**: (fill in)
- **Mission/purpose**: (fill in)
- **Asset size**: (fill in)

---

## 2. Return Requirement

| Category | Description |
|------|------|
| **Actuarial assumed rate of return** | (e.g., discount rate of a DB pension plan) |
| **Spending Rate** | (e.g., 4-5% for endowments) |
| **Inflation adjustment** | (whether purchasing power needs to be preserved) |
| **Net return requirement** | (target after fees) |

**Analysis**: (fill in detailed analysis)

---

## 3. Risk Tolerance

| Factor | Assessment |
|------|------|
| **Funded Status** | Surplus / Adequate / Underfunded |
| **Contribution flexibility** | High / Medium / Low |
| **Regulatory constraints** | (if any) |
| **Overall risk capacity** | Above average / Average / Below average |

**Key considerations**:
- (effect of surplus/deficit on risk capacity)
- (risk preferences of contributors/beneficiaries)

---

## 4. Time Horizon

| Factor | Description |
|------|------|
| **Liability duration structure** | (e.g., duration of a pension plan) |
| **Going-concern assumption** | Yes / No |
| **Phased objectives** | (list) |

---

## 5. Liquidity Requirements

| Requirement type | Amount/ratio | Time |
|----------|-----------|------|
| **Pension payments** | | |
| **Operating expenses** | | |
| **Capital Calls** | | |
| **Other commitments** | | |

**Analysis**: (fill in)

---

## 6. Legal & Regulatory

| Item | Description |
|------|------|
| **ERISA / related regulations** | (applicable laws) |
| **UPMIFA / prudent investor rule** | (applicable rules) |
| **Tax status** | Tax-exempt / Taxable |
| **Reporting requirements** | (regulatory reporting obligations) |

---

## 7. Spending Policy

| Parameter | Value |
|------|------|
| **Spending rate** | (e.g., 4-5% of asset market value) |
| **Calculation method** | Moving average / Lagged market value / Hybrid method |
| **Smoothing mechanism** | (e.g., Yale formula, 3-year average) |
| **Principal protection clause** | (whether to preserve principal purchasing power) |

**Analysis**: (fill in)

---

## 8. Board Oversight

| Responsibility | Description |
|------|------|
| **IPS approval** | Board / Investment committee |
| **Investment manager selection** | Internal / External / Hybrid |
| **Performance review frequency** | Quarterly / Annually |
| **Compliance oversight** | (fill in) |

---

## 9. Unique Circumstances

- (e.g., social/environmental impact investing requirements)
- (e.g., concentrated holding restrictions)
- (e.g., donor restriction clauses)
- (other personalized needs)

---

## 10. Asset Allocation

| Asset class | Target weight | Allowed range |
|----------|----------|----------|
| Global equity | | |
| Fixed income | | |
| Alternative investments | | |
| Real assets | | |
| Cash | | |

**Rebalancing strategy**: (fill in)

---

## 11. Benchmark

- **Composite benchmark**: (e.g., Policy Portfolio Benchmark)
- **Per-asset-class benchmarks**: (list)
- **Relative benchmark evaluation**: (fill in)

---

## 12. Monitoring & Review

- **Review frequency**: Annually (at minimum)
- **Trigger conditions**: Significant market volatility / regulatory changes / change in institutional objectives
- **IPS revision process**: (fill in)

---

*This template was auto-generated by CFA Prep CLI*
"""


class IPSBuilder:
    """
    IPS builder.
    Generates CFA Level III personal and institutional IPS templates.
    """

    def __init__(self):
        self.templates_dir = get_data_dir("templates")

    def generate(self, ips_type: str) -> str:
        """
        Generate an IPS template.

        Parameters:
            ips_type: "personal" or "institutional" (supports shorthand personal/inst)

        Returns:
            the generated file path
        """
        ips_type = ips_type.lower()
        if ips_type in ("personal", "p"):
            template = IPS_PERSONAL_TEMPLATE
            filename = "ips_personal.md"
        elif ips_type in ("institutional", "inst", "i"):
            template = IPS_INSTITUTIONAL_TEMPLATE
            filename = "ips_institutional.md"
        else:
            raise ValueError(f"Unsupported IPS type: {ips_type}, please use personal or institutional")

        content = template.format(date=today_iso())
        filepath = self.templates_dir / filename
        write_file_text(filepath, content)

        return str(filepath)

    def show_template(self, ips_type: str) -> None:
        """Display the IPS template content in the terminal"""
        ips_type = ips_type.lower()
        if ips_type in ("personal", "p"):
            print(IPS_PERSONAL_TEMPLATE.format(date=today_iso()))
        elif ips_type in ("institutional", "inst", "i"):
            print(IPS_INSTITUTIONAL_TEMPLATE.format(date=today_iso()))
        else:
            print(f"❌ Unsupported IPS type: {ips_type}")
